In [1]:
#load all modules/libraries we will use

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [3]:
#load dataset using pandas

In [4]:
d=pd.read_csv(r"C:\\COURSES\\DATA SCIENCE\\actual lessons\\Titanic-Dataset.csv")
d

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [5]:
d.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [6]:
d.describe

<bound method NDFrame.describe of      PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]>

In [7]:
d.info

<bound method DataFrame.info of      PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]>

In [8]:
d.isnull().any()

PassengerId    False
Survived       False
Pclass         False
Name           False
Sex            False
Age             True
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [9]:
d.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [10]:
d["Age"] = d["Age"].fillna(d["Age"].mean())
d["Age"]

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: Age, Length: 891, dtype: float64

In [11]:
d["Embarked"].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [12]:
e=pd.get_dummies(d["Sex"])
e

     female   male
0     False   True
1      True  False
2      True  False
3      True  False
4     False   True
..      ...    ...
886   False   True
887    True  False
888    True  False
889   False   True
890   False   True

[891 rows x 2 columns]

In [13]:
d=pd.concat([d,e], axis = 1)
d

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,female,male
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,NaN,S,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C,True,False
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S,True,False
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S,True,False
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,NaN,S,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,NaN,S,False,True
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S,True,False
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,NaN,S,True,False
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C,False,True
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,NaN,Q,False,True

In [14]:
d=d.drop(["Sex"],axis=1)
d

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,female,male
0,1,0,3,"Braund, Mr. Owen Harris",22.000000,1,0,A/5 21171,7.2500,NaN,S,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.000000,1,0,PC 17599,71.2833,C85,C,True,False
2,3,1,3,"Heikkinen, Miss. Laina",26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S,True,False
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.000000,1,0,113803,53.1000,C123,S,True,False
4,5,0,3,"Allen, Mr. William Henry",35.000000,0,0,373450,8.0500,NaN,S,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",27.000000,0,0,211536,13.0000,NaN,S,False,True
887,888,1,1,"Graham, Miss. Margaret Edith",19.000000,0,0,112053,30.0000,B42,S,True,False
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",29.699118,1,2,W./C. 6607,23.4500,NaN,S,True,False
889,890,1,1,"Behr, Mr. Karl Howell",26.000000,0,0,111369,30.0000,C148,C,False,True
890,891,0,3,"Dooley, Mr. Patrick",32.000000,0,0,370376,7.7500,NaN,Q,False,True

In [15]:
from sklearn.model_selection import train_test_split
x=d[["Age"]]
y=d["Survived"] 
x_test,x_train,y_test,y_train = train_test_split(x,y, train_size=0.9,random_state=42)

In [16]:
from sklearn.linear_model import LinearRegression 
lr= LinearRegression() 
lr.fit(x_train,y_train)

LinearRegression()

In [17]:
y_prediction=lr.predict(x_test)
y_prediction

array([0.53996498, 0.53996498, 0.18201917, 0.39748108, 0.39748108,
       0.40917709, 0.27150562, 0.29215634, 0.3541085 , 0.41606066,
       0.16136845, 0.36099207, 0.47112924, 0.34034135, 0.39196815,
       0.4298278 , 0.32657421, 0.27838919, 0.39540994, 0.32657421,
       0.39748108, 0.46080388, 0.39748108, 0.3541085 , 0.39748108,
       0.46424567, 0.11318344, 0.3541085 , 0.45047852, 0.27150562,
       0.44359495, 0.38164279, 0.16825202, 0.59620377, 0.4298278 ,
       0.36099207, 0.26462205, 0.43671138, 0.39748108, 0.4573621 ,
       0.39748108, 0.39748108, 0.39748108, 0.56749927, 0.26462205,
       0.49866354, 0.39748108, 0.40229351, 0.31280706, 0.47801282,
       0.4573621 , 0.29903991, 0.40917709, 0.34722493, 0.33345778,
       0.36787565, 0.39540994, 0.1476013 , 0.39748108, 0.30592349,
       0.39748108, 0.43671138, 0.47801282, 0.39748108, 0.39748108,
       0.39748108, 0.39748108, 0.39748108, 0.3541085 , 0.38164279,
       0.44015316, 0.39748108, 0.33345778, 0.39748108, 0.39748108,
       0.15448488, 0.44359495, 0.39748108, 0.45047852, 0.36099207,
       0.44359495, 0.47801282, 0.3541085 , 0.53996498, 0.48489639,
       0.39748108, 0.34034135, 0.48489639, 0.57438284, 0.28871455,
       0.44359495, 0.38164279, 0.42294423, 0.5606157 , 0.43671138,
       0.29215634, 0.40229351, 0.39748108, 0.39748108, 0.31280706,
       0.3541085 , 0.37475922, 0.48489639, 0.40229351, 0.25773847,
       0.36099207, 0.34034135, 0.36787565, 0.48489639, 0.52619783,
       0.18201917, 0.39540994, 0.55373212, 0.16825202, 0.46424567,
       0.39748108, 0.40229351, 0.3541085 , 0.39748108, 0.25773847,
       0.41606066, 0.39540994, 0.37475922, 0.39748108, 0.39748108,
       0.58814999, 0.4298278 , 0.2508549 , 0.4298278 , 0.39748108,
       0.39748108, 0.43671138, 0.47801282, 0.39748108, 0.4298278 ,
       0.43671138, 0.45047852, 0.59558425, 0.43671138, 0.42294423,
       0.36787565, 0.4573621 , 0.39748108, 0.39748108, 0.39748108,
       0.45047852, 0.1751356 , 0.47801282, 0.31280706, 0.20955346,
       0.47112924, 0.31280706, 0.39748108, 0.46424567, 0.36443386,
       0.40917709, 0.39748108, 0.44359495, 0.45047852, 0.24397133,
       0.39540994, 0.35066671, 0.39748108, 0.45047852, 0.25773847,
       0.41606066, 0.45047852, 0.2508549 , 0.3541085 , 0.40229351,
       0.45047852, 0.25773847, 0.32657421, 0.41606066, 0.39748108,
       0.15448488, 0.48489639, 0.40917709, 0.57438284, 0.39748108,
       0.59503356, 0.3541085 , 0.30592349, 0.34034135, 0.38852637,
       0.40229351, 0.47801282, 0.39748108, 0.33345778, 0.33345778,
       0.42294423, 0.46424567, 0.39748108, 0.26462205, 0.44359495,
       0.59503356, 0.39748108, 0.39748108, 0.58126642, 0.57438284,
       0.47112924, 0.32313242, 0.59503356, 0.39748108, 0.4573621 ,
       0.23020418, 0.39748108, 0.4298278 , 0.42294423, 0.45047852,
       0.38852637, 0.26462205, 0.47112924, 0.43671138, 0.49177996,
       0.4298278 , 0.33345778, 0.27838919, 0.18890274, 0.43671138,
       0.39748108, 0.41606066, 0.39748108, 0.34034135, 0.29903991,
       0.4573621 , 0.43671138, 0.29215634, 0.54684855, 0.54684855,
       0.39748108, 0.38164279, 0.25773847, 0.4573621 , 0.25773847,
       0.44359495, 0.38164279, 0.39748108, 0.4573621 , 0.39748108,
       0.4298278 , 0.49866354, 0.38852637, 0.4298278 , 0.23020418,
       0.40917709, 0.34034135, 0.31969063, 0.37475922, 0.24397133,
       0.49177996, 0.46424567, 0.53996498, 0.39748108, 0.39748108,
       0.39748108, 0.23020418, 0.42294423, 0.18890274, 0.39748108,
       0.29903991, 0.46424567, 0.39748108, 0.49177996, 0.30592349,
       0.48489639, 0.34722493, 0.1751356 , 0.54684855, 0.38164279,
       0.46424567, 0.40917709, 0.4573621 , 0.34722493, 0.48489639,
       0.39748108, 0.28527277, 0.39748108, 0.43671138, 0.40229351,
       0.21643704, 0.38852637, 0.39748108, 0.38164279, 0.37475922,
       0.19578632, 0.20266989, 0.39748108, 0.58126642, 0.39748108,
       0.49177996, 0.29215634, 0.30592349, 0.39540994, 0.4057353 ,
       0.43671138, 0.39540994, 0.3541085 , 0.4298278 , 0.39748108,
       0.25773847, 0.59675446, 0.43671138, 0.43671138, 0.36099207,
       0.39540994, 0.44359495, 0.39748108, 0.41606066, 0.22332061,
       0.36099207, 0.39748108, 0.39748108, 0.39748108, 0.44359495,
       0.39748108, 0.44359495, 0.2508549 , 0.37475922, 0.40229351,
       0.39748108, 0.39748108, 0.58814999, 0.50554711, 0.23020418,
       0.49866354, 0.45047852, 0.41606066, 0.39748108, 0.39748108,
       0.40917709, 0.33345778, 0.58814999, 0.43671138, 0.38164279,
       0.28871455, 0.54684855, 0.42294423, 0.40229351, 0.29215634,
       0.3541085 , 0.39748108, 0.57438284, 0.49177996, 0.20266989,
       0.32313242, 0.4298278 , 0.39748108, 0.2508549 , 0.39748108,
       0.48489639, 0.39748108, 0.32657421, 0.4298278 , 0.27838919,
       0.39748108, 0.29903991, 0.44359495, 0.47801282, 0.40229351,
       0.51931426, 0.52619783, 0.45047852, 0.47112924, 0.45047852,
       0.37475922, 0.21643704, 0.59503356, 0.45047852, 0.39748108,
       0.39748108, 0.55373212, 0.57438284, 0.11662522, 0.47801282,
       0.46424567, 0.43671138, 0.39748108, 0.36787565, 0.39748108,
       0.38852637, 0.39540994, 0.47801282, 0.53996498, 0.33345778,
       0.37475922, 0.12006701, 0.43671138, 0.20266989, 0.4573621 ,
       0.48489639, 0.40917709, 0.43671138, 0.39748108, 0.39748108,
       0.31280706, 0.47801282, 0.58814999, 0.36787565, 0.58126642,
       0.20266989, 0.38164279, 0.38852637, 0.39748108, 0.41606066,
       0.52619783, 0.44359495, 0.32657421, 0.39748108, 0.40917709,
       0.40917709, 0.39748108, 0.47112924, 0.39540994, 0.46424567,
       0.40917709, 0.3541085 , 0.39748108, 0.43671138, 0.4057353 ,
       0.43671138, 0.31280706, 0.23020418, 0.4298278 , 0.55373212,
       0.4298278 , 0.41606066, 0.43671138, 0.39748108, 0.40917709,
       0.47112924, 0.45047852, 0.39748108, 0.39748108, 0.31280706,
       0.25773847, 0.58126642, 0.39748108, 0.47801282, 0.47801282,
       0.29903991, 0.39748108, 0.39748108, 0.39748108, 0.49177996,
       0.39748108, 0.45047852, 0.57438284, 0.39748108, 0.43671138,
       0.39540994, 0.40229351, 0.43671138, 0.29215634, 0.38164279,
       0.4573621 , 0.36099207, 0.39748108, 0.39748108, 0.3541085 ,
       0.31969063, 0.44359495, 0.36787565, 0.39748108, 0.39748108,
       0.49866354, 0.39748108, 0.47801282, 0.39540994, 0.38164279,
       0.57438284, 0.58814999, 0.39748108, 0.39748108, 0.27150562,
       0.38852637, 0.27838919, 0.42294423, 0.53996498, 0.47112924,
       0.39748108, 0.45047852, 0.39748108, 0.40917709, 0.43671138,
       0.48489639, 0.39748108, 0.39748108, 0.4573621 , 0.2508549 ,
       0.58126642, 0.59675446, 0.39748108, 0.36787565, 0.47801282,
       0.29903991, 0.39748108, 0.39748108, 0.34722493, 0.4573621 ,
       0.3541085 , 0.38164279, 0.39748108, 0.42294423, 0.05123128,
       0.21987882, 0.18890274, 0.39748108, 0.47801282, 0.50210532,
       0.47112924, 0.57438284, 0.37475922, 0.4573621 , 0.5330814 ,
       0.27838919, 0.58814999, 0.40229351, 0.45047852, 0.40917709,
       0.39748108, 0.42294423, 0.37475922, 0.41606066, 0.41606066,
       0.36787565, 0.39748108, 0.39540994, 0.39540994, 0.39748108,
       0.39748108, 0.23708775, 0.38164279, 0.24397133, 0.24397133,
       0.33345778, 0.58814999, 0.29903991, 0.2508549 , 0.33345778,
       0.28527277, 0.48489639, 0.39540994, 0.53996498, 0.41606066,
       0.4573621 , 0.39748108, 0.42294423, 0.58126642, 0.27150562,
       0.3541085 , 0.39748108, 0.37820101, 0.37475922, 0.45047852,
       0.47112924, 0.09253272, 0.31280706, 0.32657421, 0.36099207,
       0.43671138, 0.33345778, 0.37820101, 0.59503356, 0.36787565,
       0.16136845, 0.4298278 , 0.39748108, 0.59503356, 0.29215634,
       0.38852637, 0.4573621 , 0.4298278 , 0.49866354, 0.42294423,
       0.39540994, 0.43671138, 0.36099207, 0.12006701, 0.39748108,
       0.4573621 , 0.47801282, 0.39748108, 0.59503356, 0.39748108,
       0.42294423, 0.4298278 , 0.39748108, 0.46424567, 0.23020418,
       0.45047852, 0.19578632, 0.23020418, 0.41606066, 0.38852637,
       0.45047852, 0.37475922, 0.5606157 , 0.56749927, 0.33345778,
       0.43326959, 0.23020418, 0.39748108, 0.39748108, 0.39540994,
       0.39748108, 0.36099207, 0.4573621 , 0.38164279, 0.49177996,
       0.45047852, 0.39748108, 0.34034135, 0.39748108, 0.4298278 ,
       0.37475922, 0.39748108, 0.47801282, 0.39748108, 0.39748108,
       0.58814999, 0.59902603, 0.42294423, 0.31969063, 0.27150562,
       0.27150562, 0.27150562, 0.57438284, 0.33345778, 0.37475922,
       0.40229351, 0.26462205, 0.39748108, 0.39748108, 0.31280706,
       0.3541085 , 0.18201917, 0.47801282, 0.47801282, 0.59730514,
       0.38164279, 0.39748108, 0.39748108, 0.39748108, 0.49177996,
       0.38852637, 0.27150562, 0.45047852, 0.51243068, 0.38164279,
       0.40917709, 0.28527277, 0.40917709, 0.31280706, 0.36099207,
       0.58814999, 0.38852637, 0.39748108, 0.39748108, 0.47112924,
       0.46424567, 0.50554711, 0.36787565, 0.39748108, 0.39748108,
       0.2508549 , 0.39748108, 0.39748108, 0.39748108, 0.40917709,
       0.4298278 , 0.47112924, 0.36099207, 0.36099207, 0.53996498,
       0.46424567, 0.31280706, 0.39540994, 0.39748108, 0.4573621 ,
       0.27838919, 0.4298278 , 0.49177996, 0.29215634, 0.34034135,
       0.21643704, 0.39748108, 0.38852637, 0.39540994, 0.39748108,
       0.50554711, 0.49177996, 0.32657421, 0.22332061, 0.47112924,
       0.29215634, 0.3541085 , 0.41606066, 0.26462205, 0.31969063,
       0.47112924, 0.37475922, 0.41606066, 0.39748108, 0.36099207,
       0.40229351, 0.39540994, 0.36787565, 0.40229351, 0.47112924,
       0.36099207, 0.39748108, 0.32657421, 0.1751356 , 0.4298278 ,
       0.42294423, 0.47801282, 0.36787565, 0.27150562, 0.40917709,
       0.43671138, 0.48489639, 0.34034135, 0.39748108, 0.32657421,
       0.45047852, 0.58814999, 0.40917709, 0.47801282, 0.40917709,
       0.47112924, 0.39748108, 0.18890274, 0.46424567, 0.29215634,
       0.39748108, 0.43671138, 0.39748108, 0.39748108, 0.33345778,
       0.42294423, 0.43671138, 0.3541085 , 0.34722493, 0.39748108,
       0.40917709, 0.47112924, 0.30592349, 0.4298278 , 0.27838919,
       0.49177996, 0.59620377, 0.45047852, 0.47112924, 0.40917709,
       0.50554711, 0.3541085 , 0.40229351, 0.31280706, 0.39748108,
       0.41606066, 0.40229351, 0.56749927, 0.45047852, 0.39748108,
       0.39540994, 0.1751356 , 0.36787565, 0.40917709, 0.39748108,
       0.29903991, 0.29215634, 0.47112924, 0.47801282, 0.38852637,
       0.39748108, 0.4573621 , 0.4298278 , 0.38164279, 0.39540994,
       0.32657421, 0.37475922, 0.3541085 , 0.27838919, 0.36787565,
       0.47112924, 0.39748108, 0.25773847, 0.39748108, 0.39748108,
       0.39748108, 0.39748108, 0.36099207, 0.36099207, 0.47801282,
       0.49177996, 0.4573621 , 0.39748108, 0.31969063, 0.50554711,
       0.4573621 ])

In [18]:
lr.coef_

array([-0.00688357])

In [19]:
lr.intercept_

0.6019171353135818

In [42]:
a=np.array([32]).reshape(-1,1)
b=lr.predict(a)
b

C:\Users\japeu\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([0.38164279])